import React from 'react'
import Head from "next/head";
import Favicon from "../public/images/Favicon.png"
import NavbarMenu from '@/component/navbar';
import Footer from '@/component/Footer';
export default function Layout({ children }) {
    
  return (
    <div>
      <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={Favicon.src} />
      </Head>
      <main>
        <NavbarMenu />

        {children}
        <Footer />
      </main>
    </div>
  );
}
